spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xepdb1
    username: ace
    password: me

mybatis:
  type-aliases-package: com.bonestew.popmate.*.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jasypt:
  encryptor:
    password: ${encrypt_key}

logging:
  level:
    com.bonestew.popmate: debug
