spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ENC(OV0B51cIHNM4LG1E1tj/OR/9p7qp4JtiaWU53oBll9g2igOKv7oTY/8c+PXcALbKdTZOY1nsQ9zy9TQN+ewAFtmCymmFuBdrEKVhJlZbWjnUFx7KIw/08x8XOz84fl+OKu/jeyN9+wM=)
    username: ENC(wBHUWwDVvq08Jpj1rnOW+w==)
    password: ENC(55txUH4/nlUxflvU8lto/42P7YyRQrf3)
  data:
    mongodb:
      uri: ENC(fD/x2SaGuMq7ZtsPQkiTkWaxD+eod8OtHZ/ZkR8BCrdQ3X7WgxJgacRKWLWNpyDc1/MWdq+/zUw+ko9PdHZaS0ne6+hljBkZqlOhLCfuDqaP7s9d8G5ZOLv5MO6QD9V1/h+/WpvjObMw1NsGYH/MB9CP5HtitAgv)
      database: popmate
    redis:
      host: localhost
      port: 6379

mybatis:
  type-aliases-package: com.bonestew.popmate.*.domain
  type-handlers-package: com.bonestew.popmate.*.persistence.typehandler
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true

jasypt:
  encryptor:
    password: ${encrypt_key}

logging:
  level:
    com.bonestew.popmate: debug

token:
  sign:
    key: popmatedsdsdsdsdddddddsdwdwdwdwdwdwdwdwdwdwdwdwdwd